### PR TITLE
Add issue template to request add-ons registration

### PR DESCRIPTION
**Pull request by nvdaes**
@CyrilleB79 maybe interested.

You can test how this looks like by creating an issue for testing in one of my repos, such as

https://github.com/nvdaes/clipContentsDesigner

Should we add some other clarifications?

Should we try to use GitHub Actions to see if the stable branch exists, or may suffice marking the checkbox?

Cheers

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Hi

I do not know anything about GitHub actions with YAML files. So my comments are just reading this description and having done looked at the form example in Clip content designer add-on.

I do not know if adding GitHub actions to make additional check is difficult or not; so I do not know if it is worth adding the following point. Anyway, they could be a plus:
* check the presence of stable branch (as you already said)
* check that `scons pot` produces a `.pot` file
* why not check translator comments (probably the add-on template should also be modified)

Is there a way to have a demo of the form created by this PR? Probably not until it is merged; just asking confirmation.

**Comment by nvdaes** [comment]
I can create a GitHub Action to make a demo in clipContentsDesigenr. GitHub Actions can run shell commands, for example: scons pot. I will create it tomorrow. In add-ons maintained by me I check if all translatable gettext messages have comments for translators. But this is not mandatory for add-ons and so probably shouldn"t be included here. But we may try to see if the stable branch exists an if scons pot runs.
In fact, we cannot demonstrate this in mrconfig repo until it is not merget, since as far as I know, forms work just in default branch. They are a beta feature.
I"ll come when I create a GitHub Action for clipContentsDesigner to check scons pot and the presence of stable branch.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
I've created a workflow (GitHub Actions) that checks out the stable branch from the nvdaaddons organization repo and runs scons and scons pot. If steps succeed, the bot of GitHub Actions makes a comment on the issue.
When we create a PR, we can see checks pass or fail, but on issues we have to go to Actions to see each workflow, what is more uncomfortable, so I think it's better to have a comment on success.
You can see [issue 33 of clipContentsDesigner](https://github.com/nvdaes/clipContentsDesigner/issues/33) used for testing.

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
Let's see if this makes this process smoother, thanks @nvdaes

**Pull request merged**
