### PR TITLE
Move scripts from ScreenReaderTranslations repo

### PR DESCRIPTION
**Pull request by feerrenrut**
Move all scripts / cron config from the [assembla screenReaderTranslations repo](https://app.assembla.com/spaces/screenReaderTranslations)

When merged the following must be updated on the server:
- [x] Update nginx config with the new location for the `scripts/webhook` file.
- [x] Manually update cron with the new `crontab.automatic` file.

Also:
- [x] Translators need to be notified that this is now the new location for updating email addresses.
- [ ] Scripts can be removed from SRT repo
- [x] `crontab.automatic` can be removed from https://github.com/nvdaaddons/addonFiles

Note for reviewers, due to the number of moved files, I recommend reviewing this commit-wise. I have separated the changes to files from the initial import of the files to make it easier to review.

Since we don't have a development server, and the design of this is quite tied to the server, this has not been tested at all. Changes have been made carefully, however issues are likely when we try to roll this out. I hope we can improve this situation with time to be able to gain confidence in the changes before they are deployed. For now the pragmatic approach is to go ahead but be ready for manually fix / clean up when running through the steps. I suggest we initially disable the cron jobs and manually trigger the commands so we can catch issues early without affecting every repository.

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]
At a glance this looks good to me. But just going ahead with merging it and running the cron jobs will be the best test.

**Comment by feerrenrut** [comment]
I think I'll disable the cron jobs first, and manually run through some of the steps to test the scripts, then re-enable cron and allow it to run on all.

**Comment by zstanecic** [comment]
Hi,
This is somewhat pisitive and negative change.
For this type of work, there should be a translations coordinator, who will add people and languages to the scripts. 
Really, we have an ongoing problem, because if we get new people, it will need intervention from someone.

**Comment by VovaMobile** [comment]
Please tell me how to translate addons now?
Previously, I commited addons translations in the same way as NVDA translations. Then the system stopped working. Accordingly, it is interesting what will change for translators in the end.

**Comment by josephsl** [comment]
Hi,

An email from Reef was sent to translations mailing list, and after someone joined us, I informed her to stay put for a while due to massive changes happening with translations workflow. Eventually these changes will trickle down to users in the future, and the community wiki must be edited when this work is done.

Thanks.

**Comment by feerrenrut** [comment]
@zstanecic rest assured, we are thinking about the workflow for adding new translators. But it is important for us to start with the most core parts of the system and work from there. For now, the process hasn't really changed, instead of committing directly to the SRT repository a PR will need to be made against this repo. This allows us and other translators to check the changes for errors that cause disruption. 

@VovaMobile The add-on translation process for add-ons has not changed. However, the issue you may be seeing is a merge conflict. The translation files for many add-ons have conflicts (changes on both the add-on side and on the 'screeen reader translations' side). This prevents the system from being able to merge in the new translations. This requires us to manually fix the problem. I hope we can achieve a more robust system in the future that does not encounter this problem.

@josephsl Thanks, yes this is an active space with more planned. I'd like to see the documentation moved to within each appropriate repository. This makes it easier for the community to help maintain the documentation / clarify common issues etc. For documentation relevant to translators, language groups can document their specific structure and process.

**Comment by feerrenrut** [comment]
Crontab has been backed up (see `nvdal10n/cron_backup.txt`)
crontab has been removed

Proceeding to merge this PR and update on server.
I'll test the crontab commands manually, and re-enable (with the updated) crontab
I'll then fix the webhook path

**Pull request merged**
